version: '3.6'
services:
    nginx:
        image: nginx:latest
        container_name: gutenberg-dev-nginx
        ports:
            - '80:80'
            - '443:443'
        volumes:
            - ./nginx/default.conf:/tmp/default.template
            - ./:/var/www/html:rw,cached
            - ./certs:/etc/certs
        depends_on:
            - wordpress
        restart: always
        entrypoint: /bin/bash -c 'cat /tmp/default.template | sed "s/\\\$$domain/${DOMAIN}/g" > /etc/nginx/conf.d/default.conf && nginx -g "daemon off;"'
    mysql:
        image: mariadb
        container_name: gutenberg-dev-mysql
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=gutenberg_dev
        restart: always
        ports:
            - '3306:3306'
    wordpress:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: gutenberg-dev-wordpress
        volumes:
            - ./:/var/www/html:rw,cached
        environment:
            - WORDPRESS_DB_NAME=gutenberg_dev
            - WORDPRESS_TABLE_PREFIX=wp_
            - WORDPRESS_DB_HOST=mysql
            - WORDPRESS_DB_PASSWORD=root
        depends_on:
            - mysql
        restart: always
    composer:
        image: composer
        container_name: ${APP_NAME}-composer
        working_dir: /var/www/html
        restart: 'no'
        volumes:
        - ./src:/var/www/html:rw,cached
